name: PMMO Simple Comfig

on:
  push:
    branches: [ "master", "feat/windows-action" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - run: pip install pyinstaller
    - run: pip install flet
    - run: flet pack PMMO_Simple_Config.py
    - uses: actions/upload-artifact@v2
      with:
        name: PMMOSimpleComfig
        path: dist/main.exe
